### ISSUE TITLE
Incompatible version error

### ISSUE THREAD

**Issue by zeeshanhanif** [pazguille/shuffle-array#12]
I'm facing following error while deploying application on heroku, it seems that shuffle-array version is not compatible with Node. Can you please guide what is the solution for it?

remote:        npm ERR! Linux 3.13.0-79-generic
remote:        npm ERR! argv 
remote:        npm ERR! node v5.9.1
remote:        npm ERR! npm  v3.7.3
remote:
remote:        **npm ERR! No compatible version found: shuffle-array@0.1.2**
remote:        npm ERR! Valid install targets:
remote:        npm ERR! 2.0.0, 0.0.1-security
remote:        npm ERR!
remote:        npm ERR!
remote:        npm ERR! If you need help, you may report this error at:
remote:        npm ERR!     <https://github.com/npm/npm/issues>
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_697d8b8fec943eeebab6cbbf6178b3dc/npm-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to .
remote:

**Comment by pazguille** [comment]
https://github.com/pazguille/shuffle-array/issues/5#issuecomment-207865446
