### ISSUE TITLE
Iterating over shuffled array gives indexes as strings

### ISSUE THREAD

**Issue by DXsmiley** [pazguille/shuffle-array#14]
If you shuffle an array in-place and then try to iterate over it with a `for .. in` loop, the indexes of the array turn out to be strings, not integers.

For example, this code:
```javascript
var shuffle = require('shuffle-array');
var array = [1, 2, 3];
shuffle(array);
for (var n in array) {
    console.log(n, ':', array[n]);
    console.log(typeof n);
}
```

produces the following output:
```
0 : 2
string
1 : 1
string
2 : 3
string
```

I'm running node.js 6.3.0 on windows.

**Comment by pazguille** [comment]
Hi @DXsmiley. This is not an issue with `shuffle-array`. `for..in` is used to iterate over the properties of a JavaScript objects and returns its keys as strings.

When you use `for..in` to iterate over an array, the keys are strings too. For example, this code:
```js
var array = [1, 2, 3];

for (var n in array) {
    console.log(n, ':', array[n]);
    console.log(typeof n);
}
```

The output will be:
```js
0 : 2
string
1 : 1
string
2 : 3
string
```
