### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by btknorr** [pazguille/shuffle-array#5]
For nodejs support.

**Comment by pazguille** [comment]
Hi @azer, When you unpublish all your modules from npm, algo unpublish this module!
I would like to get the ownership to publish itagain.
Thank you.

**Comment by azer** [comment]
@pazguille my apologizes! could you reach npm support for it?

**Comment by pazguille** [comment]
@azer, yes, I sent an email to npm support to fix it.

**Comment by gabooh** [comment]
Waiting for the package to be back on npm too.
You can use this in package.json in the mean time to use version 0.1.2

`"shuffle-array": "pazguille/shuffle-array#bd67edb"`

**Comment by pazguille** [comment]
Update:
![screen shot 2016-04-01 at 10 43 08](https://cloud.githubusercontent.com/assets/250856/14208596/9b6b10ea-f7f6-11e5-9b16-b1196d374ea8.png)

**Comment by pazguille** [comment]
shuffle-array v1.0.0 #npm module was published again!
